export default {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    NO_INTERNET: "NO_INTERNET",

    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    INCREASE_CART_ITEM_QUANTITY: "INCREASE_CART_ITEM_QUANTITY",
    DECREASE_CART_ITEM_QUANTITY: "DECREASE_CART_ITEM_QUANTITY",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADD_TO_FAVOURITE: "ADD_TO_FAVOURITE",
    REMOVE_FROM_FAVOURITE: "REMOVE_FROM_FAVOURITE",

    CREATE_ADDRESS: "CREATE_ADDRESS",
    UPDATE_ADDESS: "UPDATE_ADDESS",
    REMOVE_ADDRESS: "REMOVE_ADDRESS",
 }