export const USER_ID = 'USER_ID';
export const MOBILE_AUTH_ID = 'MOBILE_AUTH_ID'; 
export const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN';
export const EMAIL_PASS_LOGIN = 'EMAIL_PASS_LOGIN';
export const MOBILE_AUTH_LOGIN = 'MOBILE_AUTH_LOGIN'; 